# Synopsis: Storage account names need to follow the naming convention sta<bu-4><deployment stage-4><application name><appid-2><role><application name> and <role> is 11. 
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: My.Storage.NameConvention
spec:
  type:
  - Microsoft.Storage/storageAccounts
  condition:
    allOf:
      - name: '.'
        match: '^sta[a-z0-9]{20,24}$' 
        
 
---
 
# Synopsis: Storage accounts need tag with the name 'ProductOwner'
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: My.Storage.ProductOwnerTag
spec:
  type:
  - Microsoft.Storage/storageAccounts
  condition:
    field: tags.productowner
    exists: true