name: Azure ARM

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Preview-Bicep-Changes:
    runs-on: ubuntu-latest

    steps:   
    - name: Run PSRule analysis
      uses: microsoft/ps-rule@v2.9.0
      with:
        version: '1.11.1'
        modules: 'PSRule.Rules.Azure'
        inputPath: src/
        #source: deployment  
